"""modernize_automation_module_v4

Revision ID: 0b0fc81866b9
Revises: 841f565131b5
Create Date: 2026-04-02 12:46:24.909763+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b0fc81866b9'
down_revision: Union[str, None] = '841f565131b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automation_logs', sa.Column('triggered_by', sa.String(length=50), nullable=False))
    op.add_column('automation_logs', sa.Column('input_snapshot', sa.JSON(), nullable=False))
    op.drop_column('automation_logs', 'event_data')
    op.add_column('automation_rules', sa.Column('use_ai_matching', sa.Boolean(), nullable=False))
    op.add_column('automation_rules', sa.Column('ai_intent_prompt', sa.String(length=1000), nullable=True))
    op.add_column('automation_rules', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('automation_rules', sa.Column('hit_count', sa.Integer(), nullable=False))
    op.add_column('automation_rules', sa.Column('last_triggered_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'automation_rules', 'users', ['created_by'], ['id'])
    op.add_column('campaigns', sa.Column('channel', sa.String(length=50), nullable=False))
    op.add_column('campaigns', sa.Column('sent_count', sa.Integer(), nullable=False))
    op.add_column('campaigns', sa.Column('delivered_count', sa.Integer(), nullable=False))
    op.add_column('campaigns', sa.Column('opened_count', sa.Integer(), nullable=False))
    op.add_column('campaigns', sa.Column('replied_count', sa.Integer(), nullable=False))
    op.add_column('macros', sa.Column('body', sa.String(length=2000), nullable=False))
    op.add_column('macros', sa.Column('attachments', sa.JSON(), nullable=False))
    op.add_column('macros', sa.Column('is_shared', sa.Boolean(), nullable=False))
    op.drop_column('macros', 'content')
    op.add_column('workflows', sa.Column('graph', sa.JSON(), nullable=False))
    op.add_column('workflows', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('workflows', sa.Column('last_run_at', sa.DateTime(), nullable=True))
    op.add_column('workflows', sa.Column('run_count', sa.Integer(), nullable=False))
    op.drop_column('workflows', 'steps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('workflows', 'run_count')
    op.drop_column('workflows', 'last_run_at')
    op.drop_column('workflows', 'version')
    op.drop_column('workflows', 'graph')
    op.add_column('macros', sa.Column('content', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
    op.drop_column('macros', 'is_shared')
    op.drop_column('macros', 'attachments')
    op.drop_column('macros', 'body')
    op.drop_column('campaigns', 'replied_count')
    op.drop_column('campaigns', 'opened_count')
    op.drop_column('campaigns', 'delivered_count')
    op.drop_column('campaigns', 'sent_count')
    op.drop_column('campaigns', 'channel')
    op.drop_constraint(None, 'automation_rules', type_='foreignkey')
    op.drop_column('automation_rules', 'last_triggered_at')
    op.drop_column('automation_rules', 'hit_count')
    op.drop_column('automation_rules', 'created_by')
    op.drop_column('automation_rules', 'ai_intent_prompt')
    op.drop_column('automation_rules', 'use_ai_matching')
    op.add_column('automation_logs', sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('automation_logs', 'input_snapshot')
    op.drop_column('automation_logs', 'triggered_by')
    # ### end Alembic commands ###
