"""add pending_ticket_data to conversation

Revision ID: 142f3f4ccd19
Revises: d71fbdac91da
Create Date: 2026-04-15 22:33:01.925910+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142f3f4ccd19'
down_revision: Union[str, None] = 'd71fbdac91da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('pending_ticket_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'pending_ticket_data')
    # ### end Alembic commands ###
