"""add usage toggles to knowledge

Revision ID: 18a1100c1f62
Revises: f1a2b3c4d5e6
Create Date: 2026-03-25 12:50:42.538577+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a1100c1f62'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('usage_agent', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('folders', sa.Column('usage_copilot', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('folders', sa.Column('usage_help_center', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('knowledge_documents', sa.Column('usage_agent', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('knowledge_documents', sa.Column('usage_copilot', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('knowledge_documents', sa.Column('usage_help_center', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_documents', 'usage_help_center')
    op.drop_column('knowledge_documents', 'usage_copilot')
    op.drop_column('knowledge_documents', 'usage_agent')
    op.drop_column('folders', 'usage_help_center')
    op.drop_column('folders', 'usage_copilot')
    op.drop_column('folders', 'usage_agent')
    # ### end Alembic commands ###
