"""add_escalation_rules_table

Revision ID: 3742673d7980
Revises: 0b0fc81866b9
Create Date: 2026-04-02 13:32:07.466724+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3742673d7980'
down_revision: Union[str, None] = '0b0fc81866b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalation_rules',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('threshold_minutes', sa.Integer(), nullable=False),
    sa.Column('ai_frustration_enabled', sa.Boolean(), nullable=False),
    sa.Column('frustration_sensitivity', sa.Float(), nullable=False),
    sa.Column('action_assign_team', sa.Uuid(), nullable=True),
    sa.Column('action_priority', sa.String(length=20), nullable=False),
    sa.Column('action_notify_emails', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalation_rules_id'), 'escalation_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escalation_rules_id'), table_name='escalation_rules')
    op.drop_table('escalation_rules')
    # ### end Alembic commands ###
