"""add channel_data to contacts table

Revision ID: 50f1feb5f5b5
Revises: 1b6a3699ce6b
Create Date: 2026-03-17 22:56:52.522076+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f1feb5f5b5'
down_revision: Union[str, None] = '1b6a3699ce6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('channel_data', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'channel_data')
    # ### end Alembic commands ###
