"""Add is_active to api_keys

Revision ID: 6b9a2aa96809
Revises: 94b98523315a
Create Date: 2026-03-17 18:41:22.980921+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9a2aa96809'
down_revision: Union[str, None] = '94b98523315a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'is_active')
    # ### end Alembic commands ###
