"""increase business hours time column length

Revision ID: 6c595579224f
Revises: 6b9a2aa96809
Create Date: 2026-03-17 19:57:24.533444+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6c595579224f'
down_revision: Union[str, None] = '6b9a2aa96809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_hours', 'open_time',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('business_hours', 'close_time',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_hours', 'close_time',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('business_hours', 'open_time',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    # ### end Alembic commands ###
