"""add_team_permissions_and_invite_fields

Revision ID: 700d4f1fc4e6
Revises: 91ed6fe5904b
Create Date: 2026-04-03 10:04:41.337064+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700d4f1fc4e6'
down_revision: Union[str, None] = '91ed6fe5904b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('team_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'invites', 'teams', ['team_id'], ['id'])
    op.add_column('teams', sa.Column('allowed_pages', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'allowed_pages')
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.drop_column('invites', 'team_id')
    # ### end Alembic commands ###
