"""add_assigned_user_id_to_ticket

Revision ID: 9a8ce3ce2fdf
Revises: 700d4f1fc4e6
Create Date: 2026-04-03 11:49:02.939910+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8ce3ce2fdf'
down_revision: Union[str, None] = '700d4f1fc4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('assigned_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'assigned_user_id')
    # ### end Alembic commands ###
