"""add_ai_agent_system_fields

Revision ID: a116e0d86aae
Revises: 142f3f4ccd19
Create Date: 2026-04-22 12:01:43.584127+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a116e0d86aae'
down_revision: Union[str, None] = '142f3f4ccd19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_configurations',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('personality', sa.String(length=50), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('primary_goal', sa.String(length=50), nullable=False),
    sa.Column('greeting_message', sa.Text(), nullable=True),
    sa.Column('fallback_message', sa.Text(), nullable=True),
    sa.Column('collect_email_trigger', sa.String(length=50), nullable=False),
    sa.Column('collect_name_trigger', sa.String(length=50), nullable=False),
    sa.Column('max_context_messages', sa.Integer(), nullable=False),
    sa.Column('rag_enabled', sa.Boolean(), nullable=False),
    sa.Column('rag_top_k', sa.Integer(), nullable=False),
    sa.Column('rag_min_similarity', sa.Float(), nullable=False),
    sa.Column('allowed_topics', sa.JSON(), nullable=True),
    sa.Column('blocked_topics', sa.JSON(), nullable=True),
    sa.Column('escalation_keywords', sa.JSON(), nullable=True),
    sa.Column('system_prompt_template', sa.Text(), nullable=True),
    sa.Column('tools_enabled', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_index(op.f('ix_ai_configurations_id'), 'ai_configurations', ['id'], unique=False)
    op.add_column('messages', sa.Column('intent', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'metadata')
    op.drop_column('messages', 'confidence')
    op.drop_column('messages', 'intent')
    op.drop_index(op.f('ix_ai_configurations_id'), table_name='ai_configurations')
    op.drop_table('ai_configurations')
    # ### end Alembic commands ###
