"""add_ratings_and_session_fields

Revision ID: d1ee1b628c94
Revises: 7a6a6f1ad83a
Create Date: 2026-04-15 10:49:29.034246+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ee1b628c94'
down_revision: Union[str, None] = '7a6a6f1ad83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('rated_entity_type', sa.String(length=20), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ratings_agent_created', 'ratings', ['agent_id', 'created_at'], unique=False)
    op.create_index('ix_ratings_conversation', 'ratings', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    op.create_index('ix_ratings_score', 'ratings', ['score'], unique=False)
    op.create_index('ix_ratings_workspace_created', 'ratings', ['workspace_id', 'created_at'], unique=False)
    op.add_column('conversations', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_conversations_updated_desc', 'conversations', ['updated_at'], unique=False)
    op.add_column('workspaces', sa.Column('session_timeout_hours', sa.Integer(), server_default='24', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'session_timeout_hours')
    op.drop_index('ix_conversations_updated_desc', table_name='conversations')
    op.drop_column('conversations', 'closed_at')
    op.drop_index('ix_ratings_workspace_created', table_name='ratings')
    op.drop_index('ix_ratings_score', table_name='ratings')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_index('ix_ratings_conversation', table_name='ratings')
    op.drop_index('ix_ratings_agent_created', table_name='ratings')
    op.drop_table('ratings')
    # ### end Alembic commands ###
