"""add_routing_and_offline_state_to_conversation

Revision ID: d232454661fe
Revises: fcb42cc54609
Create Date: 2026-04-02 22:42:02.772610+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd232454661fe'
down_revision: Union[str, None] = 'fcb42cc54609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('routing_mode', sa.String(length=50), nullable=False, server_default='ai'))
    op.add_column('conversations', sa.Column('offline_state', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'offline_state')
    op.drop_column('conversations', 'routing_mode')
    # ### end Alembic commands ###
