"""add_identity_tracking_v2

Revision ID: d71fbdac91da
Revises: d1ee1b628c94
Create Date: 2026-04-15 22:04:44.480667+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71fbdac91da'
down_revision: Union[str, None] = 'd1ee1b628c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor_sessions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('visitor_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('landing_page', sa.Text(), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('identified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_sessions_id'), 'visitor_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_visitor_sessions_session_id'), 'visitor_sessions', ['session_id'], unique=False)
    op.create_index('ix_visitor_sessions_v_s', 'visitor_sessions', ['visitor_id', 'session_id'], unique=False)
    op.create_index(op.f('ix_visitor_sessions_visitor_id'), 'visitor_sessions', ['visitor_id'], unique=False)
    op.add_column('contacts', sa.Column('visitor_id', sa.String(length=255), nullable=True))
    # Step 1: Add as nullable
    op.add_column('contacts', sa.Column('consent_given', sa.Boolean(), nullable=True))
    # Step 2: Update existing rows
    op.execute("UPDATE contacts SET consent_given = false")
    # Step 3: Set to NOT NULL
    op.alter_column('contacts', 'consent_given', nullable=False)
    
    op.add_column('contacts', sa.Column('consent_date', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_contacts_visitor_id'), 'contacts', ['visitor_id'], unique=False)
    op.add_column('conversations', sa.Column('visitor_id', sa.String(length=255), nullable=True))
    op.add_column('conversations', sa.Column('session_id', sa.String(length=255), nullable=True))
    
    # Repeat for 'identified'
    op.add_column('conversations', sa.Column('identified', sa.Boolean(), nullable=True))
    op.execute("UPDATE conversations SET identified = false")
    op.alter_column('conversations', 'identified', nullable=False)
    
    op.add_column('conversations', sa.Column('identified_at', sa.DateTime(timezone=True), nullable=True))
    
    # Repeat for 'pending_verification'
    op.add_column('conversations', sa.Column('pending_verification', sa.Boolean(), nullable=True))
    op.execute("UPDATE conversations SET pending_verification = false")
    op.alter_column('conversations', 'pending_verification', nullable=False)
    
    op.add_column('conversations', sa.Column('claimed_email', sa.String(length=255), nullable=True))
    op.add_column('conversations', sa.Column('claimed_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversations_visitor_id'), 'conversations', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_visitor_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_column('conversations', 'claimed_name')
    op.drop_column('conversations', 'claimed_email')
    op.drop_column('conversations', 'pending_verification')
    op.drop_column('conversations', 'identified_at')
    op.drop_column('conversations', 'identified')
    op.drop_column('conversations', 'session_id')
    op.drop_column('conversations', 'visitor_id')
    op.drop_index(op.f('ix_contacts_visitor_id'), table_name='contacts')
    op.drop_column('contacts', 'consent_date')
    op.drop_column('contacts', 'consent_given')
    op.drop_column('contacts', 'visitor_id')
    op.drop_index(op.f('ix_visitor_sessions_visitor_id'), table_name='visitor_sessions')
    op.drop_index('ix_visitor_sessions_v_s', table_name='visitor_sessions')
    op.drop_index(op.f('ix_visitor_sessions_session_id'), table_name='visitor_sessions')
    op.drop_index(op.f('ix_visitor_sessions_id'), table_name='visitor_sessions')
    op.drop_table('visitor_sessions')
    # ### end Alembic commands ###
