"""add_user_id_to_knowledge

Revision ID: e9a13c7d87b2
Revises: d8e2f3a4b5c6
Create Date: 2026-03-24 21:37:40.756262+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a13c7d87b2'
down_revision: Union[str, None] = 'd8e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add user_id as nullable initially
    op.add_column('folders', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.add_column('knowledge_sources', sa.Column('user_id', sa.Uuid(), nullable=True))

    # 2. Backfill user_id from workspace owner_id
    op.execute("""
        UPDATE folders f 
        SET user_id = w.owner_id 
        FROM workspaces w 
        WHERE f.workspace_id = w.id
    """)
    op.execute("""
        UPDATE knowledge_documents kd 
        SET user_id = w.owner_id 
        FROM workspaces w 
        WHERE kd.workspace_id = w.id
    """)
    op.execute("""
        UPDATE knowledge_sources ks 
        SET user_id = w.owner_id 
        FROM workspaces w 
        WHERE ks.workspace_id = w.id
    """)

    # 3. Now set as NOT NULL
    op.alter_column('folders', 'user_id', nullable=False)
    op.alter_column('knowledge_documents', 'user_id', nullable=False)
    op.alter_column('knowledge_sources', 'user_id', nullable=False)

    # 4. Create indexes and foreign keys
    op.create_index(op.f('ix_folders_id'), 'folders', ['id'], unique=False)
    op.create_index(op.f('ix_folders_user_id'), 'folders', ['user_id'], unique=False)
    op.create_foreign_key(None, 'folders', 'users', ['user_id'], ['id'])
    
    op.create_index(op.f('ix_knowledge_chunks_id'), 'knowledge_chunks', ['id'], unique=False)
    op.drop_constraint('knowledge_chunks_document_id_fkey', 'knowledge_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_chunks', 'knowledge_documents', ['document_id'], ['id'], ondelete='CASCADE')
    
    op.alter_column('knowledge_documents', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_knowledge_documents_id'), 'knowledge_documents', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_user_id'), 'knowledge_documents', ['user_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_documents', 'users', ['user_id'], ['id'])
    
    op.drop_index('knowledge_embeddings_vector_idx', table_name='knowledge_embeddings', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_knowledge_embeddings_id'), 'knowledge_embeddings', ['id'], unique=False)
    op.drop_constraint('knowledge_embeddings_chunk_id_fkey', 'knowledge_embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_embeddings', 'knowledge_chunks', ['chunk_id'], ['id'], ondelete='CASCADE')
    
    op.create_index(op.f('ix_knowledge_sources_user_id'), 'knowledge_sources', ['user_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_sources', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_sources', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_sources_user_id'), table_name='knowledge_sources')
    op.drop_column('knowledge_sources', 'user_id')
    op.drop_constraint(None, 'knowledge_embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_embeddings_chunk_id_fkey'), 'knowledge_embeddings', 'knowledge_chunks', ['chunk_id'], ['id'])
    op.drop_index(op.f('ix_knowledge_embeddings_id'), table_name='knowledge_embeddings')
    op.create_index(op.f('knowledge_embeddings_vector_idx'), 'knowledge_embeddings', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint(None, 'knowledge_documents', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_documents_user_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_id'), table_name='knowledge_documents')
    op.alter_column('knowledge_documents', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('knowledge_documents', 'user_id')
    op.drop_constraint(None, 'knowledge_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_chunks_document_id_fkey'), 'knowledge_chunks', 'knowledge_documents', ['document_id'], ['id'])
    op.drop_index(op.f('ix_knowledge_chunks_id'), table_name='knowledge_chunks')
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_index(op.f('ix_folders_user_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_id'), table_name='folders')
    op.drop_column('folders', 'user_id')
    # ### end Alembic commands ###
