"""Add CRM fields to contacts

Revision ID: ec615eddf062
Revises: f9cb9a36cf8b
Create Date: 2026-04-30 12:59:19.235390+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec615eddf062'
down_revision: Union[str, None] = 'f9cb9a36cf8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('contacts', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('timezone', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('status', sa.String(length=50), server_default='prospect', nullable=False))
    op.add_column('contacts', sa.Column('lifecycle_stage', sa.String(length=50), server_default='lead', nullable=False))
    op.add_column('contacts', sa.Column('vip', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('contacts', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contacts', sa.Column('last_channel_used', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('total_conversations', sa.Integer(), server_default='0', nullable=False))
    op.add_column('contacts', sa.Column('total_tickets', sa.Integer(), server_default='0', nullable=False))
    op.add_column('contacts', sa.Column('open_tickets_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('contacts', sa.Column('avg_response_time', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('satisfaction_score', sa.Float(), nullable=True))
    op.add_column('contacts', sa.Column('lifetime_value', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('contacts', sa.Column('custom_fields', sa.JSON(), nullable=True))
    op.add_column('contacts', sa.Column('metadata_', sa.JSON(), nullable=True))
    op.add_column('contacts', sa.Column('assigned_agent_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'contacts', 'users', ['assigned_agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'assigned_agent_id')
    op.drop_column('contacts', 'metadata_')
    op.drop_column('contacts', 'custom_fields')
    op.drop_column('contacts', 'lifetime_value')
    op.drop_column('contacts', 'satisfaction_score')
    op.drop_column('contacts', 'avg_response_time')
    op.drop_column('contacts', 'open_tickets_count')
    op.drop_column('contacts', 'total_tickets')
    op.drop_column('contacts', 'total_conversations')
    op.drop_column('contacts', 'last_channel_used')
    op.drop_column('contacts', 'last_seen_at')
    op.drop_column('contacts', 'vip')
    op.drop_column('contacts', 'lifecycle_stage')
    op.drop_column('contacts', 'status')
    op.drop_column('contacts', 'language')
    op.drop_column('contacts', 'timezone')
    op.drop_column('contacts', 'title')
    op.drop_column('contacts', 'avatar_url')
    # ### end Alembic commands ###
