"""add_keywords_to_escalation_rules

Revision ID: f13ca6033101
Revises: 3742673d7980
Create Date: 2026-04-02 13:55:56.536078+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f13ca6033101'
down_revision: Union[str, None] = '3742673d7980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escalation_rules', sa.Column('keywords', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('escalation_rules', 'keywords')
    # ### end Alembic commands ###
