"""add ai prompt to workspace

Revision ID: f1a2b3c4d5e6
Revises: e9a13c7d87b2
Create Date: 2026-03-25 00:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a2b3c4d5e6'
down_revision: Union[str, None] = 'e9a13c7d87b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('ai_system_prompt', sa.String(length=1000), nullable=True))
    op.add_column('workspaces', sa.Column('ai_tone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'ai_tone')
    op.drop_column('workspaces', 'ai_system_prompt')
    # ### end Alembic commands ###
