"""add_multi_channel_fields

Revision ID: f9cb9a36cf8b
Revises: a116e0d86aae
Create Date: 2026-04-23 10:03:43.558612+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9cb9a36cf8b'
down_revision: Union[str, None] = 'a116e0d86aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('primary_channel', sa.String(length=50), nullable=True))
    op.execute("UPDATE conversations SET primary_channel = 'widget'")
    op.alter_column('conversations', 'primary_channel', nullable=False)
    
    op.add_column('conversations', sa.Column('channels_used', sa.JSON(), nullable=True))
    op.execute("UPDATE conversations SET channels_used = '[]'")
    
    op.add_column('conversations', sa.Column('external_conversation_id', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('media_url', sa.String(length=1024), nullable=True))
    op.add_column('messages', sa.Column('media_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'media_type')
    op.drop_column('messages', 'media_url')
    op.drop_column('conversations', 'external_conversation_id')
    op.drop_column('conversations', 'channels_used')
    op.drop_column('conversations', 'primary_channel')
    # ### end Alembic commands ###
