"""add_pro_widget_security_fields

Revision ID: fcb42cc54609
Revises: f13ca6033101
Create Date: 2026-04-02 22:32:03.085925+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb42cc54609'
down_revision: Union[str, None] = 'f13ca6033101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('public_key', sa.String(length=100), nullable=True))
    op.add_column('workspaces', sa.Column('encrypted_secret_key', sa.String(length=500), nullable=True))
    op.add_column('workspaces', sa.Column('encrypted_previous_secret_key', sa.String(length=500), nullable=True))
    op.add_column('workspaces', sa.Column('secret_key_created_at', sa.DateTime(), nullable=True))
    op.add_column('workspaces', sa.Column('previous_key_expires_at', sa.DateTime(), nullable=True))
    op.add_column('workspaces', sa.Column('allowed_domains', sa.JSON(), nullable=False, server_default='[]'))
    # Use a unique index that allows NULLs (default behavior in Postgres)
    op.create_index(op.f('ix_workspaces_public_key'), 'workspaces', ['public_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_public_key'), table_name='workspaces')
    op.drop_column('workspaces', 'allowed_domains')
    op.drop_column('workspaces', 'previous_key_expires_at')
    op.drop_column('workspaces', 'secret_key_created_at')
    op.drop_column('workspaces', 'encrypted_previous_secret_key')
    op.drop_column('workspaces', 'encrypted_secret_key')
    op.drop_column('workspaces', 'public_key')
    # ### end Alembic commands ###
