"""add missing workspace ai identity fields

Revision ID: workspaces_ai_fields_v2
Revises: head_merge_2024
Create Date: 2026-03-31 01:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'workspaces_ai_fields_v2'
down_revision: Union[str, None] = 'head_merge_2024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('ai_custom_instructions', sa.String(length=2000), nullable=True))
    op.add_column('workspaces', sa.Column('company_description', sa.String(length=2000), nullable=True))
    op.add_column('workspaces', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('workspaces', sa.Column('ai_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'ai_settings')
    op.drop_column('workspaces', 'industry')
    op.drop_column('workspaces', 'company_description')
    op.drop_column('workspaces', 'ai_custom_instructions')
    # ### end Alembic commands ###
